# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#+TITLE: Indexed
#+HTML: <a href="https://repology.org/project/emacs%3Aorg-node/versions"> <img src="https://repology.org/badge/vertical-allrepos/emacs%3Aorg-node.svg" alt="Packaging status" align="right"> </a>

An efficient cache of metadata about all your Org files.

Builds fast.  My =M-x indexed-reset=:

#+begin_example
indexed: Analyzed 160616 lines in 10734 entries (3397 with ID)
         in 2394 files in 1.37s (+ 0.16s to build SQLite DB)
#+end_example

This library came from asking myself "what could I move out of [[https://github.com/meedstrom/org-node][org-node]], that'd make sense in core?"  Maybe a proposal for upstream, or at least a PoC.

Many Org plugins now do reinvent the wheel, when it comes to keeping track of some or many files and what may be in them.

Example: org-roam's DB, org-node's hash tables, orgrr's hash tables, ..., and some just re-run grep all the time, which still leads to writing elisp to cross-reference the results with something useful.

And let's not talk about the org-agenda... (Try putting 2000 files into =org-agenda-files=!)  It needs to open each file in real-time to know anything about them, so everyday commands grind to a halt.

** Quick overview

Data will exist after setup akin to this and you wait a second or two.

#+begin_src elisp
(setq indexed-org-dirs '("~/org" "~/Sync/notes"))
(indexed-updater-mode)
(indexed-roam-mode) ;; optional
#+end_src

Two different APIs to access the same data.

- sql
- elisp

Why two?  It's free.  When the data has been gathered anyway, there is no reason to /only/ insert it into a SQLite db, nor /only/ put it in a hash table.

Hash table is nicer for simple lookups (and slightly faster).  SQL excels for complex lookups.

As a bonus, it's fairly easy to design your own SQL database, so this library does not lock you in.  Included is one that matches [[https://github.com/org-roam/org-roam][org-roam's]] database perfectly, and a future milestone might be adding one that matches [[https://github.com/ndwarshuis/org-sql][org-sql]].

To use SQL, see [[https://github.com/meedstrom/indexed#appendix-i-a-sqlite-database-for-free][Appendix I]].  For the elisp API, see [[https://github.com/meedstrom/indexed#appendix-ii-lisp-api][Appendix II]].

** Data only

A design choice: Indexed *only* delivers data.  It could easily ship conveniences like... let's call it a function "indexed-goto":

#+begin_src elisp
(defun indexed-goto (entry)
  (find-file (indexed-file-name entry))
  (goto-char (indexed-pos entry))
#+end_src

but in my experience, that will spiral into dozens of lines over time, to handle a variety of edge cases, and then it will no longer be universally applicable.  Maybe you prefer to handle edge cases different than I do.

So, it is up to you to write your own "goto" function and all else to do with user interaction.

** No Org at init

A design choice: Indexed does not use Org code to analyze your files, but a [[https://github.com/meedstrom/indexed/blob/main/indexed-org-parser.el][custom, more dumb parser]].  That's for three reasons:

1. *Fast init*.  Since I want Emacs init to be fast, it's not allowed to load Org, but I still want to be able to use a command like =org-node-find= to browse my Org stuff, before deciding to actually jump into an Org file.

   That means the data must be able to exist, before Org has loaded.
   
   - Future milestone: I want to be told at init if there's a dangling Org clock somewhere.  Or a deadline.

2. *Robustness.*  Many users heavily customize Org, so no surprise that it sometimes breaks.  In my experience, it's very nice then to have an alternative way to browse that does not depend on a functional Org setup.

3. *Fast rebuild.*  As they say, there are two hard things in computer science: cache invalidation and naming things^{note1}.
   
   Indexed must update its cache as the user saves, renames and deletes files.  Not a difficult problem, until you realize that files may change due to a Git operation, OS file operations, a =rm= command on the terminal, edits by another Emacs instance, or even remote edits by Logseq.

   A solution could be a filesystem watcher, but that feels simultaneously brittle and overkill to me.

   A robust approach to cache invalidation is to avoid trying: ensure that a full rebuild is fast enough that you can just do /that/ instead.

   In fact, =indexed-updater-mode= does a bit of both, because it is still important that saving a file does not lag;  it does its best to update only the necessary tables on save, and an idle timer causes a full reset every now and then.

   - {}^{note1}: I sometimes feel I failed at naming this library! Got opinions/ideas?  [[https://github.com/meedstrom/indexed/issues/4][Leave a comment!]] 

** Appendix I: A SQLite database, for free

Included are two designs:

1. A drop-in for [[https://github.com/org-roam/org-roam][org-roam's]] =(org-roam-db)=, called =(indexed-roam)=.
2. Our own experimental =(indexed-orgdb)=.
   - Are you a SQL and Org user?  Please write [[https://github.com/meedstrom/indexed/issues/1][what you think should go in a good DB]].
     - There is prior art on the matter at [[https://github.com/ndwarshuis/org-sql/blob/80bea9996de7fa8bc7ff891a91cfaff91111dcd8/org-sql.el#L141][org-sql]], but your story is still welcome!

*** Quick start with =indexed-roam=
UPDATE NOTICE [2025-03-23 Sun 16:44]:  Hopefully a lot of bugs went away. Function =(indexed-roam)= now always returns an EmacSQL connection, and takes no arguments.

**** Without org-roam installed

Activating the mode creates an in-memory database by default.

#+begin_src elisp
(indexed-roam-mode)
#+end_src

Test that it works:

#+begin_src elisp
(emacsql (indexed-roam) [:select * :from files :limit 10])
#+end_src

**** With org-roam installed

To end your dependence on =org-roam-db-sync=, you can set the following.  It will overwrite the "org-roam.db" file.

#+begin_src elisp
(setq org-roam-db-update-on-save nil)
(setq indexed-roam-overwrite t)
(indexed-roam-mode)
#+end_src

Now, you have a new, all-fake org-roam.db!  Test that it works:

#+begin_src elisp
(org-roam-db-query [:select * :from files :limit 10])
#+end_src

N/B: because =(equal (org-roam-db) (indexed-roam))=, the above is equivalent to these:

#+begin_src elisp
(emacsql (org-roam-db) [:select * :from files :limit 10])
(emacsql (indexed-roam) [:select * :from files :limit 10])
#+end_src

Note if you use multiple Emacsen simultaneously, there's a *known issue* with error "attempt to write a readonly database".  Get unstuck with =M-: (org-roam-db--close-all)= if that happens.

*** Quick start with =indexed-orgdb=

This DB is a bit different, subject to redesign.

#+begin_src elisp
(indexed-orgdb-mode)
#+end_src

Note it probably does *not* work with EmacSQL, just the Emacs 29+ built-in =sqlite-select=.

In practice, you can often translate a statement like

#+begin_src elisp
(org-roam-db-query [:select tag :from tags :where (= id $s1)] id)
#+end_src

to

#+begin_src elisp
(sqlite-select (indexed-orgdb) "select tag from tags where id = ?;" (list id))
#+end_src

or if you like mysterious aliases,

#+begin_src elisp
(indexed-orgdb "select tag from tags where id = ?;" id)
#+end_src

There are several differences between this and org-roam's DB. You can compare, if you if you enable both

#+begin_src elisp
(indexed-roam-mode)
(indexed-orgdb-mode)
#+end_src

and then use command =M-x indexed-list-db-contents=.

** Appendix II: Lisp API

There are three types of objects: /file-data/, /org-entry/ and /org-link/.  Some functions operate on more than one type.

Functions of no argument

- indexed-org-files
  - Return all /file-data/ objects
- indexed-org-entries
  - Return all /org-entry/ objects
- indexed-org-id-nodes
  - Return all /org-entry/ objects that have an ID
- indexed-org-links-and-citations
  - Return all /org-link/ objects
- indexed-org-links
  - Return all /org-link/ objects with a type such as =id:= or =https:=

Polymorphic functions
- indexed-pos
- indexed-file-name
- indexed-file-data
- indexed-file-title
- indexed-file-title-or-basename
- indexed-file-mtime

Functions operating on raw file paths
- indexed-entry-near-lnum-in-file
- indexed-entry-near-pos-in-file
- indexed-id-nodes-in
- indexed-entries-in

Functions operating on raw id
- indexed-entry-by-id
- indexed-links-from

Functions operating on raw titles
- indexed-id-node-by-title

Functions operating on FILE-DATA
- indexed-mtime

Functions operating on ORG-LINK
- indexed-dest
- indexed-type
- indexed-heading-above
- indexed-id-nearby
  - (old alias: =indexed-origin=.  Org-roam calls the same thing "source" and org-node calls it "origin", but both terms presume an ID-centric design to everything, and make less sense when you allow for the absence of IDs.)

Functions operating on ENTRY
- indexed-deadline
- indexed-heading-lvl
- indexed-id-links-to
- indexed-olpath
- indexed-olpath-with-self
- indexed-olpath-with-self-with-title
- indexed-olpath-with-title
- indexed-priority
- indexed-properties
- indexed-property
- indexed-property-assert
- indexed-roam-aliases
- indexed-roam-reflinks-to -- needs =indexed-roam-mode=
- indexed-roam-refs -- needs =indexed-roam-mode=
- indexed-root-heading-to
- indexed-scheduled
- indexed-tags
- indexed-tags-inherited
- indexed-tags-local
- indexed-todo-state
- indexed-toptitle

Hooks

- indexed-pre-full-reset-functions
- indexed-post-full-reset-functions
- indexed-record-file-functions
- indexed-record-entry-functions
- indexed-record-link-functions

Hooks used when =indexed-updater-mode= is enabled

- indexed-pre-incremental-update-functions
- indexed-post-incremental-update-functions
- indexed-forget-file-functions
- indexed-forget-entry-functions
- indexed-forget-link-functions

*** Extension: indexed-x.el

A separate file =indexed-x.el= is loaded when you enable =indexed-updater-mode=.

It is separate because =indexed-updater-mode= is not strictly necessary -- it could be replaced by a simple timer that calls =indexed-reset= every 20 seconds, or whatever you deem suitable.

The file also ships some extra tools.

**** Programmer tool: Instantly index thing at point

You may want to call the following functions after inserting entries or links in a custom way, if they need to become indexed instantly without waiting for user to save the buffer:

- indexed-x-ensure-entry-at-point-known
- indexed-x-ensure-link-at-point-known

Examples of when those are useful is when you write a command like =org-node-extract-subtree=, or subroutine like =org-node-backlink--add-in-target=.

*** Extension: indexed-roam.el

Enabled by =indexed-roam-mode=.  Explained elsewhere.

** Appendix III: Make your own database
Steps:

1. Read indexed-roam.el as a reference implementation

   - See how it looks up the indexed data it needs.
   - See which things require a =prin1-to-string=.
   - See how arguments are ultimately passed to =sqlite-execute=.

     Alas, this file got a bit hard to read after squeezing for performance, but it can be done simpler. [TODO: write a simple reference impl]

2. Hook your own DB-creator onto =indexed-post-full-reset-functions=, or just on a repeating timer or some suitable hook.

3. Done!

** Appendix IV: User stuff

Modes

- indexed-updater-mode
- indexed-roam-mode

Config settings

- indexed-warn-title-collisions
- indexed-seek-link-types
- indexed-org-dirs
- indexed-org-dirs-exclude
- indexed-roam-overwrite

Commands

- indexed-list-dead-id-links
- indexed-list-title-collisions
- indexed-list-problems
- indexed-list-entries
- indexed-list-db-contents
- indexed-reset

** Tip: Fully inform org-id
# XXX update the blob link

Never sit through a slow =M-x org-id-update-id-locations= again!

#+begin_src elisp
(add-hook 'indexed-record-entry-functions #'indexed-x-snitch-to-org-id)
#+end_src

This tells org-id about all IDs that Indexed can find under =indexed-org-dirs=.

That's very good, because if you had clicked an ID-link that org-id did not know about, it would react by running =org-id-update-id-locations=, making Emacs appear to hang for as long as a minute.

Never had this problem?  If you came here from org-node or org-roam,  that's because they solve this problem for you.  I did not want to do it in this library for two reasons:

1. packaging hygiene
2. the org-id [[https://github.com/meedstrom/org-node/blob/a889ede01dbcf22668bfe718037619732169245f/org-node.el#L992-1037][Schrodinger's cat bug]]
